name: ci

on:
  - push
  - pull_request

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
        working-directory: ./client
      - run: pnpm build
        working-directory: ./client
      - run: pnpm test
        working-directory: ./client

  e2e-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
        working-directory: ./client
      - run: pnpm playwright install --with-deps
        working-directory: ./client
      - run: pnpm test:e2e
        working-directory: ./client
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30
