name: ci

on:
  - push
  - pull_request

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: cd client
      - run: pnpm build
      - run: pnpm test

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: cd client
      - run: pnpm build
      - run: pnpm test:e2e
